// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Class struct {
	ID    int32
	Index string
	Name  string
	Url   sql.NullString
}

type Spell struct {
	ID            int32
	Index         string
	Name          string
	Range         sql.NullString
	Material      sql.NullString
	Ritual        sql.NullBool
	Duration      sql.NullString
	Concentration sql.NullBool
	CastingTime   sql.NullString
	Level         sql.NullInt32
	AttackType    sql.NullString
	School        pqtype.NullRawMessage
	Desc          []string
	HigherLevel   []string
	Components    []string
	Damage        pqtype.NullRawMessage
	Url           string
	UpdatedAt     sql.NullTime
}

type SpellClass struct {
	SpellID int32
	ClassID int32
}

type SpellSubclass struct {
	SpellID    int32
	SubclassID int32
}

type Subclass struct {
	ID    int32
	Index string
	Name  string
	Url   sql.NullString
}
