// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spellcalls.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const getSpell = `-- name: GetSpell :one
SELECT name, range, material, ritual, duration, concentration, casting_time, "level", attack_type, school, "desc", higher_level, components, damage
FROM spells
WHERE "index" = $1
`

type GetSpellRow struct {
	Name          string
	Range         sql.NullString
	Material      sql.NullString
	Ritual        sql.NullBool
	Duration      sql.NullString
	Concentration sql.NullBool
	CastingTime   sql.NullString
	Level         sql.NullInt32
	AttackType    sql.NullString
	School        pqtype.NullRawMessage
	Desc          []string
	HigherLevel   []string
	Components    []string
	Damage        pqtype.NullRawMessage
}

func (q *Queries) GetSpell(ctx context.Context, index string) (GetSpellRow, error) {
	row := q.db.QueryRowContext(ctx, getSpell, index)
	var i GetSpellRow
	err := row.Scan(
		&i.Name,
		&i.Range,
		&i.Material,
		&i.Ritual,
		&i.Duration,
		&i.Concentration,
		&i.CastingTime,
		&i.Level,
		&i.AttackType,
		&i.School,
		pq.Array(&i.Desc),
		pq.Array(&i.HigherLevel),
		pq.Array(&i.Components),
		&i.Damage,
	)
	return i, err
}

const getSpellsClass = `-- name: GetSpellsClass :many
SELECT s.name, s.url
FROM spells AS s
JOIN spell_classes AS sc ON sc.spell_id = s.id
JOIN classes AS c ON c.id = sc.class_id
WHERE c."index" = $1
`

type GetSpellsClassRow struct {
	Name string
	Url  string
}

func (q *Queries) GetSpellsClass(ctx context.Context, index string) ([]GetSpellsClassRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpellsClass, index)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpellsClassRow
	for rows.Next() {
		var i GetSpellsClassRow
		if err := rows.Scan(&i.Name, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellsConcentration = `-- name: GetSpellsConcentration :many
SELECT name, url
FROM spells
WHERE concentration = 't'
`

type GetSpellsConcentrationRow struct {
	Name string
	Url  string
}

func (q *Queries) GetSpellsConcentration(ctx context.Context) ([]GetSpellsConcentrationRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpellsConcentration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpellsConcentrationRow
	for rows.Next() {
		var i GetSpellsConcentrationRow
		if err := rows.Scan(&i.Name, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellsLevel = `-- name: GetSpellsLevel :many
SELECT name, url
FROM spells
WHERE "level" = $1
`

type GetSpellsLevelRow struct {
	Name string
	Url  string
}

func (q *Queries) GetSpellsLevel(ctx context.Context, level sql.NullInt32) ([]GetSpellsLevelRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpellsLevel, level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpellsLevelRow
	for rows.Next() {
		var i GetSpellsLevelRow
		if err := rows.Scan(&i.Name, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellsSubclass = `-- name: GetSpellsSubclass :many
SELECT s.name, s.url
FROM spells AS s
JOIN spell_subclasses AS ss ON ss.spell_id = s.id
JOIN subclasses AS sc ON sc.id = ss.subclass_id
WHERE sc."index" = $1
`

type GetSpellsSubclassRow struct {
	Name string
	Url  string
}

func (q *Queries) GetSpellsSubclass(ctx context.Context, index string) ([]GetSpellsSubclassRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpellsSubclass, index)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpellsSubclassRow
	for rows.Next() {
		var i GetSpellsSubclassRow
		if err := rows.Scan(&i.Name, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
